version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_ts_app
    ports:
      - "3000:3000"  
      - "9229:9229" # Depuration port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0  
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rutter
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"  
    volumes:
      - dbdata:/var/lib/mysql  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:
